FROM node:18-alpine

# Set working directory to Expo project
WORKDIR /app/web

# Install Expo CLI globally
RUN npm install -g expo-cli

# Install project dependencies
COPY ./web/package.json ./web/yarn.lock ./
RUN yarn install --legacy-peer-deps

# Copy all project sources
COPY ./web .

# Expose Expo development server port
EXPOSE 19006

# Start Expo in web mode
CMD ["npx", "expo", "start", "--web"]
