services:
  supabase:
    build:
      context: .
      dockerfile: Dockerfile.supabase
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["supabase"]
    env_file:
      - .env
    ports:
      - "54321:54321"
      - "54322:54322"
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=http://localhost:54321
        - VITE_SUPABASE_ANON_KEY=service-anon-test-key
    env_file:
      - .env
    ports:
      - "3000:80"
    depends_on:
      - supabase
