version: "3.9"

services:
  supabase:
    build:
      context: .
      dockerfile: Dockerfile.supabase
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    entrypoint: ["supabase", "start"]
    env_file:
      - .env
    ports:
      - "54321:54321"
      - "54322:54322"
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    volumes:
      - ./web:/app/web
      - /app/web/node_modules  # Prevent overwriting container node_modules
    working_dir: /app/web
    command: npm run dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - supabase
    restart: unless-stopped
