version: '3.9'
services:
  supabase:
    image: supabase/cli:latest
    command: start
    volumes:
      - ./supabase:/workspace/supabase
    env_file:
      - .env
    ports:
      - "54321:54321"
      - "54322:54322"
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    env_file:
      - .env
    ports:
      - "3000:80"
    depends_on:
      - supabase
