FROM node:18-alpine

WORKDIR /app

# Install deps from web
COPY ./web/package.json ./web/package-lock.json* ./web/

WORKDIR /app/web
RUN npm install --legacy-peer-deps

# Copy all web source files
COPY ./web .



CMD ["npm", "run", "dev"]
