# Generated by Faladesk Task B102

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_b101_core_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("auth", "Autenticação"),
                            ("messaging", "Mensageria"),
                            ("tickets", "Tickets"),
                            ("automation", "Automações"),
                            ("analytics", "Analytics"),
                            ("admin", "Administração"),
                        ],
                        default="auth",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permissão",
                "verbose_name_plural": "Permissões",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("department", "Departamento"),
                            ("team", "Equipe"),
                            ("ticket_queue", "Fila de tickets"),
                        ],
                        default="global",
                        max_length=32,
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Papel",
                "verbose_name_plural": "Papéis",
                "unique_together": {("tenant", "slug"), ("tenant", "name")},
            },
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("global", "Global"),
                            ("department", "Departamento"),
                            ("team", "Equipe"),
                            ("conversation", "Conversa"),
                            ("ticket", "Ticket"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("scope_id", models.UUIDField(blank=True, null=True)),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.role",
                    ),
                ),
                (
                    "tenant_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="core.tenantuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atribuição de Papel",
                "verbose_name_plural": "Atribuições de Papel",
                "unique_together": {("tenant_user", "role", "scope_type", "scope_id")},
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("constraints", models.JSONField(blank=True, default=dict)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="core.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="core.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permissão de Papel",
                "verbose_name_plural": "Permissões de Papel",
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                related_name="roles",
                through="core.RolePermission",
                to="core.permission",
            ),
        ),
    ]
