apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-adapter
  namespace: faladesk
  labels:
    app: faladesk
    component: email-adapter
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faladesk
      component: email-adapter
  template:
    metadata:
      labels:
        app: faladesk
        component: email-adapter
    spec:
      containers:
        - name: email-adapter
          image: your-docker-registry/faladesk-email-adapter:latest
          ports:
            - containerPort: 3000
          env:
            - name: SUPABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: faladesk-config
                  key: VITE_SUPABASE_URL
            - name: SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  name: faladesk-secrets
                  key: SUPABASE_SERVICE_ROLE_KEY
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
