apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: faladesk
  labels:
    app: faladesk
    component: frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faladesk
      component: frontend
  template:
    metadata:
      labels:
        app: faladesk
        component: frontend
    spec:
      containers:
        - name: frontend
          image: your-docker-registry/faladesk-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: EXPO_PUBLIC_SUPABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: faladesk-config
                  key: EXPO_PUBLIC_SUPABASE_URL
            - name: EXPO_PUBLIC_SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: faladesk-secrets
                  key: EXPO_PUBLIC_SUPABASE_ANON_KEY
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
