name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install frontend deps
        run: |
          cd web
          npm install
      - name: Run frontend tests
        run: |
          cd web
          npm run test -- --run
      - name: Run edge function tests
        run: |
          cd supabase/functions
          deno test -A
